-- Uzbekistan Legal Content Seeding
-- Real laws and cases from Uzbekistan Civil, Criminal, and Administrative Codes

-- Insert Laws (Qonunlar)
INSERT INTO laws (uuid, title, code_name, article_number, full_text, summary, interpretation, legal_domain, subcategory, tags, importance_level, difficulty_level, effective_date, is_current) VALUES
-- Civil Code Articles
('550e8400-e29b-41d4-a716-446655440001', 'Fuqarolik Kodeksi - Shartnoma erkinligi', 'Fuqarolik Kodeksi', '357', 
'Shartnomalar erkinligi fuqarolarning va fuqarolik bo''lmagan shaxslarning o''z xohishlari bilan shartnoma tuzish, o''zlarining majburiyatlarini belgilash, o''z huquqlarini himoya qilish va majburiyatlarni bajarish huquqini anglatadi. Shartnomalar erkinligi fuqarolarning va fuqarolik bo''lmagan shaxslarning o''z xohishlari bilan shartnoma tuzish, o''zlarining majburiyatlarini belgilash, o''z huquqlarini himoya qilish va majburiyatlarni bajarish huquqini anglatadi.',
'Shartnoma erkinligi - fuqarolarning o''z xohishlari bilan shartnoma tuzish huquqi',
'Shartnoma erkinligi O''zbekiston Respublikasi Konstitutsiyasida mustahkamlangan bo''lib, fuqarolarning va fuqarolik bo''lmagan shaxslarning o''z xohishlari bilan shartnoma tuzish, o''zlarining majburiyatlarini belgilash, o''z huquqlarini himoya qilish va majburiyatlarni bajarish huquqini anglatadi.',
'civil', 'contract', ARRAY['shartnoma', 'erkinlik', 'fuqaro', 'huquq'], 'high', 'medium', '1996-04-01', true),

('550e8400-e29b-41d4-a716-446655440002', 'Fuqarolik Kodeksi - Tovar-mulk huquqi', 'Fuqarolik Kodeksi', '234', 
'Tovar-mulk huquqi tovarlarga va boshqa mol-mulkka nisbatan fuqarolarning va fuqarolik bo''lmagan shaxslarning o''zlarining xohishlariga ko''ra egalik qilish, foydalanish, tasarruf etish va buyurtma berish huquqlarini, shuningdek, ularning o''zlarining xohishlariga ko''ra o''zlarining mol-mulkiga tegishli huquqlarini cheklashni belgilaydi.',
'Tovar-mulk huquqi - tovarlar va mol-mulkka egalik qilish huquqi',
'Tovar-mulk huquqi O''zbekiston Respublikasi Fuqarolik kodeksining 234-moddasida belgilangan bo''lib, tovarlarga va boshqa mol-mulkka nisbatan fuqarolarning va fuqarolik bo''lmagan shaxslarning o''zlarining xohishlariga ko''ra egalik qilish, foydalanish, tasarruf etish va buyurtma berish huquqlarini anglatadi.',
'civil', 'property', ARRAY['tovar', 'mol-mulk', 'egalik', 'huquq'], 'high', 'medium', '1996-04-01', true),

('550e8400-e29b-41d4-a716-446655440003', 'Fuqarolik Kodeksi - Majburiyatlarni bajarish', 'Fuqarolik Kodeksi', '366', 
'Majburiyatlarni bajarish majburiyati majburiyatlarni to''g''ri va o''z vaqtida bajarishni, shuningdek, to''g''ri va o''z vaqtida bajarilmagani uchun qonunda belgilangan javobgarlikni o''z zimmasiga olishni anglatadi. Majburiyatlarni bajarish majburiyati qonun hujjatlarida, shartnomalarda yoki boshqa huquqiy hujjatlarda belgilangan talablarga muvofiq amalga oshirilishi kerak.',
'Majburiyatlarni bajarish - qonuniy majburiyatlarni o''z vaqtida bajarish',
'Majburiyatlarni bajarish majburiyati O''zbekiston Respublikasi Fuqarolik kodeksining 366-moddasida mustahkamlangan bo''lib, majburiyatlarni to''g''ri va o''z vaqtida bajarishni, shuningdek, to''g''ri va o''z vaqtida bajarilmagani uchun qonunda belgilangan javobgarlikni o''z zimmasiga olishni anglatadi.',
'civil', 'obligations', ARRAY['majburiyat', 'bajarish', 'javobgarlik', 'qonun'], 'high', 'medium', '1996-04-01', true),

-- Criminal Code Articles
('550e8400-e29b-41d4-a716-446655440004', 'Jinoyat Kodeksi - O''g''irlik', 'Jinoyat Kodeksi', '169', 
'O''g''irlik - boshqa kishining mulkini o''zlashtirish maqsadida yashirincha olib qochish. O''g''irlik qilingan mol-mulkning qiymati yirik miqyosda bo''lsa, o''g''irlik yirik miqyosda deb hisoblanadi. O''g''irlik qilish uchun jinoiy javobgarlikka tortish O''zbekiston Respublikasi Jinoyat kodeksining 169-moddasida belgilangan.',
'O''g''irlik - boshqa kishining mulkini o''zlashtirish',
'O''g''irlik - bu boshqa kishining mulkini o''zlashtirish maqsadida yashirincha olib qochish jinoyati. O''g''irlik qilish uchun jinoiy javobgarlikka tortish mol-mulkning qiymatiga qarab belgilanadi.',
'criminal', 'theft', ARRAY['o''g''irlik', 'mol-mulk', 'jinoyat', 'javobgarlik'], 'high', 'high', '1994-09-01', true),

('550e8400-e29b-41d4-a716-446655440005', 'Jinoyat Kodeksi - Tazyiq', 'Jinoyat Kodeksi', '135', 
'Tazyiq - jismoniy yoki ruhiy azob-uqbatlar qilish orqali shaxsni o''z yoki boshqa shaxslar manfaatini himoya qilish maqsadini amalga oshirishga majbur qilish. Tazyiq qilish uchun jinoiy javobgarlikka tortish O''zbekiston Respublikasi Jinoyat kodeksining 135-moddasida belgilangan.',
'Tazyiq - jismoniy yoki ruhiy azob-uqbatlar qilish',
'Tazyiq - bu jismoniy yoki ruhiy azob-uqbatlar qilish orqali shaxsni o''z yoki boshqa shaxslar manfaatini himoya qilish maqsadini amalga oshirishga majbur qilish jinoyati.',
'criminal', 'torture', ARRAY['tazyiq', 'azob-uqbat', 'jismoniy', 'ruhiy'], 'high', 'high', '1994-09-01', true),

('550e8400-e29b-41d4-a716-446655440006', 'Jinoyat Kodeksi - Poroxlanish', 'Jinoyat Kodeksi', '168', 
'Poroxlanish - o''g''irlik yoki talonchilik qilish maqsadida o''zini davlat xizmatchisi yoki xizmat vazifasini bajaruvchi shaxs sifatida ko''rsatish. Poroxlanish qilish uchun jinoiy javobgarlikka tortish O''zbekiston Respublikasi Jinoyat kodeksining 168-moddasida belgilangan.',
'Poroxlanish - o''zini davlat xizmatchisi sifatida ko''rsatish',
'Poroxlanish - bu o''g''irlik yoki talonchilik qilish maqsadida o''zini davlat xizmatchisi yoki xizmat vazifasini bajaruvchi shaxs sifatida ko''rsatish jinoyati.',
'criminal', 'fraud', ARRAY['poroxlanish', 'davlat xizmatchisi', 'o''g''irlik', 'talonchilik'], 'high', 'high', '1994-09-01', true),

-- Administrative Code Articles
('550e8400-e29b-41d4-a716-446655440007', 'Ma''muriy Huquq Buzarliklar Kodeksi - Huquqbuzarlik to''g''risidagi majburiyatlarni bajarish', 'Ma''muriy Huquq Buzarliklar Kodeksi', '205', 
'Huquqbuzarlik to''g''risidagi majburiyatlarni bajarish majburiyati fuqarolarning, fuqarolik bo''lmagan shaxslarning va mansabdor shaxslarning O''zbekiston Respublikasi Ma''muriy huquqbuzarliklar kodeksida nazarda tutilgan majburiyatlarni o''z vaqtida va to''liq bajarishlarini anglatadi.',
'Huquqbuzarlik majburiyatlari - ma''muriy huquqbuzarliklarga rioya qilish',
'Huquqbuzarlik to''g''risidagi majburiyatlarni bajarish majburiyati fuqarolarning va mansabdor shaxslarning ma''muriy huquqbuzarliklarga rioya qilishlarini anglatadi.',
'administrative', 'compliance', ARRAY['huquqbuzarlik', 'majburiyat', 'bajarish', 'mansabdor'], 'high', 'medium', '1995-09-01', true),

('550e8400-e29b-41d4-a716-446655440008', 'Ma''muriy Huquq Buzarliklar Kodeksi - Davlat tomonidan berilgan ruxsatsiz faoliyat', 'Ma''muriy Huquq Buzarliklar Kodeksi', '191', 
'Davlat tomonidan berilgan ruxsatsiz faoliyat qilish - qonun hujjatlarida belgilangan tartibda ruxsat olinmagan faoliyat turlarini amalga oshirish. Ruxsat olinmagan faoliyat qilish uchun ma''muriy javobgarlikka tortish O''zbekiston Respublikasi Ma''muriy huquqbuzarliklar kodeksining 191-moddasida belgilangan.',
'Ruxsatsiz faoliyat - davlat ruxsatisiz faoliyat yuritish',
'Davlat tomonidan berilgan ruxsatsiz faoliyat qilish - bu qonun hujjatlarida belgilangan tartibda ruxsat olinmagan faoliyat turlarini amalga oshirish ma''muriy huquqbuzarligi.',
'administrative', 'licensing', ARRAY['ruxsat', 'faoliyat', 'davlat', 'litsenziya'], 'high', 'medium', '1995-09-01', true),

-- Additional Civil Code Articles
('550e8400-e29b-41d4-a716-446655440009', 'Fuqarolik Kodeksi - Shartnomaning tuzilishi', 'Fuqarolik Kodeksi', '361', 
'Shartnoma yozma shaklda tuziladi. Yozma shaklda tuzilgan shartnoma tomonlar tomonidan imzolanishi va shartnomaning mazmunini to''liq aks ettirishi kerak. Shartnomaning tuzilishi tomonlarning o''zaro kelishuviga asoslanadi.',
'Shartnomaning tuzilishi - yozma shaklda va imzolangan shartnoma',
'Shartnoma yozma shaklda tuzilishi va tomonlar tomonidan imzolanishi O''zbekiston Respublikasi Fuqarolik kodeksining 361-moddasida belgilangan.',
'civil', 'contract', ARRAY['shartnoma', 'tuzilish', 'yozma', 'imzo'], 'medium', 'low', '1996-04-01', true),

('550e8400-e29b-41d4-a716-446655440010', 'Fuqarolik Kodeksi - Majburiyatlarning o''z vaqtida bajarilmasligi', 'Fuqarolik Kodeksi', '367', 
'Majburiyatlarni o''z vaqtida bajarilmagani uchun qonunda belgilangan javobgarlikni o''z zimmasiga olish. Majburiyatlarni o''z vaqtida bajarilmagani uchun javobgarlik majburiyatlarning mohiyatiga va buzilish darajasiga qarab belgilanadi.',
'Majburiyatlarni o''z vaqtida bajarish - qonuniy muddatda bajarish',
'Majburiyatlarni o''z vaqtida bajarilmagani uchun javobgarlik O''zbekiston Respublikasi Fuqarolik kodeksining 367-moddasida belgilangan.',
'civil', 'obligations', ARRAY['majburiyat', 'o''z vaqtida', 'bajarish', 'javobgarlik'], 'high', 'medium', '1996-04-01', true),

-- Additional Criminal Code Articles
('550e8400-e29b-41d4-a716-446655440011', 'Jinoyat Kodeksi - Talonchilik', 'Jinoyat Kodeksi', '164', 
'Talonchilik - boshqa kishining mulkini ochiq olib qochish. Talonchilik qilingan mol-mulkning qiymati yirik miqyosda bo''lsa, talonchilik yirik miqyosda deb hisoblanadi. Talonchilik qilish uchun jinoiy javobgarlikka tortish O''zbekiston Respublikasi Jinoyat kodeksining 164-moddasida belgilangan.',
'Talonchilik - boshqa kishining mulkini ochiq olib qochish',
'Talonchilik - bu boshqa kishining mulkini ochiq olib qochish jinoyati. O''g''irlikdan farqi shundaki, talonchilik ochiq amalga oshiriladi.',
'criminal', 'robbery', ARRAY['talonchilik', 'ochiq olish', 'mol-mulk', 'jinoyat'], 'high', 'high', '1994-09-01', true),

('550e8400-e29b-41d4-a716-446655440012', 'Jinoyat Kodeksi - Qalbakilik pul ishlab chiqarish', 'Jinoyat Kodeksi', '176', 
'Qalbakilik pul ishlab chiqarish - O''zbekiston Respublikasining milliy valyutasini qalbakilab ishlab chiqarish, qalbakilik pul muomalasi qilish yoki shunday puldan foydalanish. Qalbakilik pul ishlab chiqarish uchun jinoiy javobgarlikka tortish O''zbekiston Respublikasi Jinoyat kodeksining 176-moddasida belgilangan.',
'Qalbakilik pul - milliy valyutani qalbakilab ishlab chiqarish',
'Qalbakilik pul ishlab chiqarish - bu O''zbekiston Respublikasining milliy valyutasini qalbakilab ishlab chiqarish, qalbakilik pul muomalasi qilish yoki shunday puldan foydalanish jinoyati.',
'criminal', 'counterfeiting', ARRAY['qalbakilik', 'pul', 'valyuta', 'muomala'], 'high', 'high', '1994-09-01', true),

-- Additional Administrative Code Articles
('550e8400-e29b-41d4-a716-446655440013', 'Ma''muriy Huquq Buzarliklar Kodeksi - Soliq to''lash majburiyatini buzish', 'Ma''muriy Huquq Buzarliklar Kodeksi', '215', 
'Soliq to''lash majburiyatini buzish - qonunda belgilangan tartibda soliqlarni to''lamaslik yoki toliq to''lamaslik. Soliq to''lash majburiyatini buzish uchun ma''muriy javobgarlikka tortish O''zbekiston Respublikasi Ma''muriy huquqbuzarliklar kodeksining 215-moddasida belgilangan.',
'Soliq to''lash - davlat byudjetiga soliqlarni to''lash majburiyati',
'Soliq to''lash majburiyatini buzish - bu qonunda belgilangan tartibda soliqlarni to''lamaslik yoki toliq to''lamaslik ma''muriy huquqbuzarligi.',
'administrative', 'tax', ARRAY['soliq', 'to''lash', 'majburiyat', 'byudjet'], 'high', 'medium', '1995-09-01', true),

('550e8400-e29b-41d4-a716-446655440014', 'Ma''muriy Huquq Buzarliklar Kodeksi - Atrof-muhitni muhofaza qilish talablarini buzish', 'Ma''muriy Huquq Buzarliklar Kodeksi', '89', 
'Atrof-muhitni muhofaza qilish talablarini buzish - atrof-muhitni muhofaza qilish sohasidagi qonun hujjatlarida belgilangan talablarni buzish. Atrof-muhitni muhofaza qilish talablarini buzish uchun ma''muriy javobgarlikka tortish O''zbekiston Respublikasi Ma''muriy huquqbuzarliklar kodeksining 89-moddasida belgilangan.',
'Atrof-muhitni muhofaza qilish - ekologik talablarga rioya qilish',
'Atrof-muhitni muhofaza qilish talablarini buzish - bu ekologik qonun hujjatlarida belgilangan talablarni buzish ma''muriy huquqbuzarligi.',
'administrative', 'environmental', ARRAY['atrof-muhit', 'muhofaza', 'ekologiya', 'talablar'], 'medium', 'medium', '1995-09-01', true),

-- Family Law Articles (Civil Code)
('550e8400-e29b-41d4-a716-446655440015', 'Fuqarolik Kodeksi - Nikoh va oila', 'Fuqarolik Kodeksi', '1', 
'Oila - nikoh asosida tuzilgan, qonunga muvofiq shaxslarning o''zaro huquq va majburiyatlari. Oilada er va xotinning teng huquqlari kafolatlanadi. Oilaviy munosabatlar qonun hujjatlarida belgilangan tartibda tartibga solinadi.',
'Oila - nikoh asosida tuzilgan munosabatlar',
'Oila - bu nikoh asosida tuzilgan, qonunga muvofiq shaxslarning o''zaro huquq va majburiyatlari. Oila O''zbekiston Respublikasi Konstitutsiyasi va Fuqarolik kodeksida himoya qilinadi.',
'civil', 'family', ARRAY['nikoh', 'oila', 'huquq', 'majburiyat'], 'high', 'medium', '1996-04-01', true),

('550e8400-e29b-41d4-a716-446655440016', 'Fuqarolik Kodeksi - Ajrim', 'Fuqarolik Kodeksi', '126', 
'Ajrim - nikohni sud tomonidan bekor qilish. Ajrim qilish uchun asoslar qonunda belgilangan. Ajrim qilingan hollarda nikohning oqibatlari sud tomonidan hal etiladi.',
'Ajrim - nikohni sud tomonidan bekor qilish',
'Ajrim - bu nikohni sud tomonidan bekor qilish jarayoni. Ajrim qilish uchun asoslar O''zbekiston Respublikasi Fuqarolik kodeksining 126-moddasida belgilangan.',
'civil', 'family', ARRAY['ajrim', 'nikoh', 'sud', 'bekor qilish'], 'high', 'medium', '1996-04-01', true),

('550e8400-e29b-41d4-a716-446655440017', 'Fuqarolik Kodeksi - Vorislik', 'Fuqarolik Kodeksi', '1120', 
'Vorislik - vafot etgan shaxsning mulkini qonunda belgilangan tartibda meros qilib olish. Vorislik qilish huquqi Konstitutsiya va Fuqarolik kodeksida kafolatlanadi.',
'Vorislik - meros qilib olish huquqi',
'Vorislik - bu vafot etgan shaxsning mulkini qonunda belgilangan tartibda meros qilib olish huquqi. Vorislik qilish O''zbekiston Respublikasi Fuqarolik kodeksining 1120-moddasida belgilangan.',
'civil', 'inheritance', ARRAY['vorislik', 'meros', 'vafot', 'mulk'], 'high', 'medium', '1996-04-01', true),

-- Labor Law Articles
('550e8400-e29b-41d4-a716-446655440018', 'Mehnat Kodeksi - Mehnat shartnomasi', 'Mehnat Kodeksi', '77', 
'Mehnat shartnomasi - ishchi va ish beruvchi o''rtasida tuziladigan yozma shartnoma. Mehnat shartnomasi ishchi va ish beruvchining huquq va majburiyatlarini belgilaydi. Mehnat shartnomasi yozma shaklda tuzilishi va imzolanishi kerak.',
'Mehnat shartnomasi - ishchi va ish beruvchi o''rtasidagi shartnoma',
'Mehnat shartnomasi - bu ishchi va ish beruvchi o''rtasida tuziladigan yozma shartnoma bo''lib, ularning huquq va majburiyatlarini belgilaydi.',
'civil', 'labor', ARRAY['mehnat', 'shartnoma', 'ishchi', 'ish beruvchi'], 'high', 'medium', '1995-07-01', true),

('550e8400-e29b-41d4-a716-446655440019', 'Mehnat Kodeksi - Ish haqi to''lash', 'Mehnat Kodeksi', '133', 
'Ish haqi to''lash - ish beruvchining ishchiga mehnat shartnomasida belgilangan ishlari uchun pul mukofotini to''lash majburiyati. Ish haqi o''z vaqtida va to''liq to''lanishi kerak.',
'Ish haqi - mehnat uchun pul mukofoti',
'Ish haqi - bu ish beruvchining ishchiga mehnat shartnomasida belgilangan ishlari uchun pul mukofotini to''lash majburiyati. Ish haqi O''zbekiston Respublikasi Mehnat kodeksining 133-moddasida belgilangan.',
'civil', 'labor', ARRAY['ish haqi', 'to''lash', 'pul mukofoti', 'mehnat'], 'high', 'medium', '1995-07-01', true),

('550e8400-e29b-41d4-a716-446655440020', 'Mehnat Kodeksi - Ishdan bo''shatish', 'Mehnat Kodeksi', '240', 
'Ishdan bo''shatish - ish beruvchining mehnat shartnomasini bir tomonlama bekor qilishi. Ishdan bo''shatish qonunda belgilangan asoslarda amalga oshirilishi kerak.',
'Ishdan bo''shatish - mehnat shartnomasini bekor qilish',
'Ishdan bo''shatish - bu ish beruvchining mehnat shartnomasini bir tomonlama bekor qilishi. Ishdan bo''shatish O''zbekiston Respublikasi Mehnat kodeksining 240-moddasida belgilangan.',
'civil', 'labor', ARRAY['ishdan bo''shatish', 'beker qilish', 'mehnat shartnomasi'], 'high', 'medium', '1995-07-01', true);

-- Insert Clauses
INSERT INTO clauses (uuid, title, content, clause_type, risk_level, importance_level, is_template, template_category, usage_count, recommended_modifications, common_issues, created_by) VALUES
('660e8400-e29b-41d4-a716-446655440001', 'Majburiyatlarni bajarish kafolati', 
'Shartnomaning bajarilmaganligi uchun javobgarlik tomonlarning majburiyatlarini belgilaydi. Majburiyatlarni bajarish kafolati sifatida bank kafolati yoki garov qo''yilishi mumkin.', 
'guarantee', 'medium', 'high', true, 'commercial', 0, 
ARRAY['bank kafolati qo''shish', 'garov talab qilish', 'sanktsiyalarni belgilash'], 
ARRAY['kafolatni aniq belgilamaslik', 'javobgarlikni cheklamaslik'], 1),

('660e8400-e29b-41d4-a716-446655440002', 'Maxfiylik shartnomasi', 
'Ikkala tomon ham shartnoma mavzusi va shartlarini maxfiy saqlashga majbur. Maxfiylikning buzilishi jinoiy javobgarlikka olib kelishi mumkin.', 
'confidentiality', 'medium', 'high', true, 'commercial', 0, 
ARRAY['maxfiylikni kuchaytirish', 'sanktsiyalarni belgilash', 'tovon to''lash'], 
ARRAY['maxfiylik chegarasini belgilamaslik', 'himoya choralari yetarli emas'], 1),

('660e8400-e29b-41d4-a716-446655440003', 'Nizolash shartnomasi', 
'Barcha nizolar Toshkent shahar sudida ko''rib chiqiladi. Nizolash xarajatlari mag''lubiyaz tomonidan to''lanadi.', 
'dispute', 'low', 'medium', true, 'commercial', 0, 
ARRAY['nizolash usulini o''zgartirish', 'xarajatlarni taqsimlash'], 
ARRAY['nizolash joyini aniq belgilamaslik', 'xarajatlar tengsizligi'], 1),

('660e8400-e29b-41d4-a716-446655440004', 'Kredit shartnomasi', 
'Kredit miqdori, foiz stavkasi va qaytarish tartibi belgilanadi. Kreditni o''z vaqtida qaytarmagani uchun foizlar hisoblanadi.', 
'financial', 'high', 'high', true, 'financial', 0, 
ARRAY['foiz stavkasini tekshirish', 'kafolat talab qilish', 'jaroima shartlari'], 
ARRAY['foiz stavkasi noaniq', 'qaytarish jadvali mavjud emas'], 1),

('660e8400-e29b-41d4-a716-446655440005', 'Ijaraga berish shartnomasi', 
'Ijarachi mulkni to''g''ri foydalanishi va ijaraga to''lovni o''z vaqtida to''lashi kerak. Ijarachi mulkni buzgani uchun javobgarlikni o''z zimmasiga oladi.', 
'lease', 'medium', 'medium', true, 'property', 0, 
ARRAY['zaxira pulini belgilash', 'buzilish uchun javobgarlik', 'tekshiruv shartlari'], 
ARRAY['tekshiruv shartlari yo''q', 'buzilish holatlari aniq emas'], 1);

-- Insert Cases
INSERT INTO cases (uuid, title, description, case_number, court_name, decision_date, legal_domain, difficulty_level, tags, facts, legal_issues, applicable_laws, decision, reasoning, precedent_value, estimated_time, min_xp_required, xp_reward, status, is_featured, created_at, created_by) VALUES
('770e8400-e29b-41d4-a716-446655440001', 'Toshkent shahar "Bunyodkor" sudi shartnoma nizoli', 
'Ikki kompaniya o''rtasida tuzilgan shartnoma bo''yicha kelishmovchilik. Shartnomaning bajarilmaganligi sababli bir kompaniya sudga murojaat qildi. Sud shartnomaning qonunga muvofiq ekanligini va javobgar tomoni majburiyatlarini bajarishi kerakligini hukm qildi.', 
'2023/452', 'Toshkent shahar "Bunyodkor" tumani sudi', '2023-10-15', 'civil', 'medium', 
ARRAY['shartnoma', 'majburiyat', 'nizol', 'sud'], 
'"A" kompaniyasi "B" kompaniyasi bilan 2023-yil 1-yanvarda 10 million so''m miqdorida qurilish ishlari shartnomasini tuzdi. "A" kompaniyasi shartnomani bajarib, ishlarni tugatdi, ammo "B" kompaniyasi to''lovni to''liq qilmadi. "A" kompaniyasi bir necha bor to''lovni talab qildi, ammo "B" kompaniyasi pul mablag''lari yetarli emasligini da''vo etdi.', 
'1. Shartnoma majburiyatlarini bajarish masalasi. 2. To''lovning o''z vaqtida amalga oshirilmasligi. 3. Shartnomaning buzilishi uchun javobgarlik masalasi.', 
ARRAY['357', '361', '366', '367'], 
'"B" kompaniyasi shartnoma bo''yicha "A" kompaniyasiga 10 million so''m miqdorida qarz 10 million so''m miqdorida to''lovni 30 kun ichida to''lashi, shuningdek, kechikish uchun 2 foiz miqdora jorima to''lashi shart. Sud "B" kompaniyasi shartnoma majburiyatlarini buzgani uchun javobgar tomon ekanligini hukm qildi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 361-moddasiga asosan, shartnomaning yozma shaklda tuzilganligini va tomonlar tomonidan imzolanganligini tasdiqladi. Shartnomaning 366-moddasiga ko''ra, majburiyatlarni bajarish majburiyati bor. "B" kompaniyasi majburiyatni bajarmagani uchun 367-moddasiga muvofiq javobgarlikni o''z zimmasiga olishi kerak. Sud shuningdek, 367-moddasiga ko''ra, majburiyatlarni o''z vaqtida bajarilmagani uchun belgilangan jorimani to''lashni buyurdi.', 
'high', 45, 50, 100, 'active', true, '2023-10-15', 1),

('770e8400-e29b-41d4-a716-446655440002', 'Samarqand viloyati "Oqdaryoq" tumani sudi o''g''irlik ishi', 
'Jinoiy ish bo''yicha sud hukmi. Ayolning uyidan qimmatbaho buyumlarni o''g''irlagani uchun sud 3 yilga ozodlikdan mahrum qilish hukmini chiqardi. Ayol o''g''irlangan buyumlarni qaytarib berdi va jabrlanuvchiga tovon to''ladi.', 
'2023/123', 'Samarqand viloyati "Oqdaryoq" tumani sudi', '2023-09-20', 'criminal', 'high', 
ARRAY['o''g''irlik', 'jinoyat', 'sud', 'hukm'], 
'Toshent shahrida yashovchi 35 yoshli ayol 2023-yil 8-avgustda Samarqand viloyatiga qarindoshlariga tashrif buyurdi. U Samarqand shahridagi qarindoshining uyida qolayotgan vaqtida, uy egasi uydan chiqib ketganda, ayol uydan oltin taqincha, 2 ta oltin uzuk va 1 ta oltin sirg''ani olib qochdi. Qimmatbaho buyumlarning umumiy qiymati 50 million so''mni tashkil etdi. Qarindoshi ayolning xatti-harakatini ko''rib, politsiyaga murojaat qildi.', 
'1. O''g''irlik jinoyatining sodir etilishi. 2. Jinoyatning miqyosi. 3. Jabrlanuvchiga yetkazilgan zararni. 4. Ayolning gunohini tan olishi.', 
ARRAY['169', '35', '61'], 
'Ayol o''g''irlik jinoyatini tan oldi va o''g''irlangan barcha buyumlarni qaytarib berdi. Jabrlanuvchi ayoldan kechirim so''radi. Sud ayolning gunohni tan olishini, jabrlanuvchiga yetkazilgan zararni to''lashini va o''g''irlangan buyumlarni qaytarib berishini inobatga olib, O''zbekiston Respublikasi Jinoyat kodeksining 62-moddasiga muvofiq, 3 yilga ozodlikdan mahrum qilish hukmini chiqardi.', 
'Sud O''zbekiston Respublikasi Jinoyat kodeksining 169-moddasiga ko''ra, o''g''irlik - boshqa kishining mulkini o''zlashtirish maqsadida yashirincha olib qochishdir. Ayolning harakatlari 169-moddasining tarkibiy belgilariga to''liq mos keladi. Ayolning gunohni tan olishi va jabrlanuvchiga yetkazilgan zararni to''lashi 62-moddasiga muvofiq yengillashtiruvchi holat sifatida inobatga olindi.', 'medium', 30, 75, 150, 'active', true, '2023-09-20', 1),

('770e8400-e29b-41d4-a716-446655440003', 'Farg''ona viloyati "Beshariq" tumani sudi poroxlanish ishi', 
'Davlat xizmatchisi sifatida ko''rsatib, fuqarolardan pul talab qilgan shaxs sudlanmoqda. Sud shaxsni poroxlanishda aybdor deb topdi va 5 yilga ozodlikdan mahrum qilish hukmini chiqardi.', 
'2023/289', 'Farg''ona viloyati "Beshariq" tumani sudi', '2023-11-05', 'criminal', 'high', 
ARRAY['poroxlanish', 'davlat xizmatchisi', 'porox', 'sud'], 
'Farg''ona viloyati "Beshariq" tumani IIBB 1-bo''limi inspektori 30 yoshli erkak 2023-yil iyun oyidan boshlab o''z vazifasidan foydalanib, fuqarolardan porox talab qila boshladi. U fuqarolarning savdo joylarini tekshirish bahonasida ularning qonunga zid ravishda faoliyat yuritayotganini da''vo qilib, har bir fuqarodan 1 million so''mdan 5 million so''mgacha pul talab qildi. Jami 15 ta fuqarodan 45 million so''m porox olgani aniqlandi.', 
'1. Poroxlanish jinoyatining sodir etilishi. 2. Davlat xizmatchisi sifatida ko''rsatish. 3. Porox miqdori va muddati. 4. Jabrlanuvchilar soni va yetkazilgan zarar.', 
ARRAY['168', '28', '205', '206'], 
'Sud shaxsning poroxlanishda aybdor ekanligini tasdiqladi. U porox olgan pulni qaytarib beradi va jabrlanuvchilarga tovon to''lashi kerak. Sud shaxsning davlat xizmatchisi sifatidagi maqomini bekor qilish hukmini chiqardi.', 
'Sud O''zbekiston Respublikasi Jinoyat kodeksining 168-moddasiga ko''ra, poroxlanish - o''g''irlik yoki talonchilik qilish maqsadida o''zini davlat xizmatchisi yoki xizmat vazifasini bajaruvchi shaxs sifatida ko''rsatishdir. Inspektorning harakatlari 168-moddasining tarkibiy belgilariga to''liq mos keladi. Porox miqdori yirik miqyosda bo''lgani uchun 168-moddasining 3-qismi qo''llanildi.', 'high', 40, 100, 200, 'active', true, '2023-11-05', 1),

('770e8400-e29b-41d4-a716-446655440004', 'Buxoro viloyati "Kogon" tumani sudi tazyiq ishi', 
'Jismoniy azob-uqbatlar qilish orqali shaxsni majbur qilish jinoyati bo''yicha sud hukmi. Ayolni tazyiq qilgan shaxs 7 yilga ozodlikdan mahrum qilindi.', 
'2023/156', 'Buxoro viloyati "Kogon" tumani sudi', '2023-08-10', 'criminal', 'high', 
ARRAY['tazyiq', 'azob-uqbat', 'jismoniy', 'ruhiy'], 
'Buxoro viloyati "Kogon" tumani yashovchi 45 yoshli erkak 2023-yil mart oyidan boshlab o''zining 25 yoshli xotinini tazyiqqa soldi. U xotinini kunduzi va kechasi ishga borishga ruxsat bermadi, uni uyda qamab qo''ydi. Xotinning qochishga urinishlarini pichanlab, uni kaltaklash, qo''llari bilan urib, ochlikdan ochgacha ovqat bermadi. Xotinning qarindoshlari bu holatni politsiyaga xabar berishdi.', 
'1. Tazyiq jinoyatining sodir etilishi. 2. Jismoniy va ruhiy azob-uqbatlar. 3. Shaxsni majbur qilish. 4. Jabrlanuvchining ahvoli.', 
ARRAY['135', '45', '46', '47'], 
'Sud erkakni tazyiq qilishda aybdor deb topdi. U 7 yilga ozodlikdan mahrum qilindi va jabrlanuvchi xotinga 20 million so''m miqdorida tovon to''lashi belgilandi.', 
'Sud O''zbekiston Respublikasi Jinoyat kodeksining 135-moddasiga ko''ra, tazyiq - jismoniy yoki ruhiy azob-uqbatlar qilish orqali shaxsni o''z yoki boshqa shaxslar manfaatini himoya qilish maqsadini amalga oshirishga majbur qilishdir. Erkakning xotiniga nisbatan sodir etgan harakatlari 135-moddasining tarkibiy belgilariga to''liq mos keladi.', 'high', 35, 80, 160, 'active', true, '2023-08-10', 1),

('770e8400-e29b-41d4-a716-446655440005', 'Xorazm viloyati "Xiva" tumani sudi talonchilik ishi', 
'Ochiq olib qochish yo''li bilan mol-mulk o''g''irlash jinoyati bo''yicha sud hukmi. Uch kishi 4 yildan 6 yilgacha ozodlikdan mahrum qilindi.', 
'2023/234', 'Xorazm viloyati "Xiva" tumani sudi', '2023-07-15', 'criminal', 'high', 
ARRAY['talonchilik', 'ochiq olish', 'mol-mulk', 'guruh'], 
'Xorazm viloyati "Xiva" tumani yashovchi 3 nafar shaxs 2023-yil iyun oyida kechqurun "Xiva" shahridagi kafe kirib, kassadan 30 million so''m naqd pul olib qochdilar. Ular qurol bilan tahdid qilib, kassirni qo''rqitishdi. Politsiya tez orada kelib, jinoyatchilarni qo''lga oldi. Ulardan o''g''irlangan pul va qurol topildi.', 
'1. Talonchilik jinoyatining sodir etilishi. 2. Qurol bilan tahdid qilish. 3. Guruh sifatida jinoyat sodir etish. 4. O''g''irlangan mulkning qiymati.', 
ARRAY['164', '165', '27', '62'], 
'Sud uchala shaxsni talonchilik qilishda aybdor deb topdi. Ularga 4 yildan 6 yilgacha ozodlikdan mahrum qilish hukmi chiqarildi. O''g''irlangan pul kassaga qaytarildi.', 
'Sud O''zbekiston Respublikasi Jinoyat kodeksining 164-moddasiga ko''ra, talonchilik - boshqa kishining mulkini ochiq olib qochishdir. Shaxslarning qurol bilan tahdid qilib, kassadan pul olib qochishlari 164-moddasining tarkibiy belgilariga to''liq mos keladi. Guruh sifatida jinoyat sodir etgani uchun 27-moddasi qo''llanildi.', 'high', 30, 70, 140, 'active', true, '2023-07-15', 1),

('770e8400-e29b-41d4-a716-446655440006', 'Qashqadaryo viloyati "Qarshi" tumani sudi qalbakilik pul ishi', 
'Qalbakilik pul ishlab chiqarish va muomalasi qilish jinoyati bo''yicha sud hukmi. Shaxs 8 yilga ozodlikdan mahrum qilindi.', 
'2023/345', 'Qashqadaryo viloyati "Qarshi" tumani sudi', '2023-12-01', 'criminal', 'high', 
ARRAY['qalbakilik', 'pul', 'muomala', 'valyuta'], 
'Qashqadaryo viloyati "Qarshi" tumani yashovchi 40 yoshli erkak 2023-yil sentyabr oyidan boshlab qalbakilik pul ishlab chiqarish bilan shug''ullanadi. U kompyuter va printer yordamida 100 ming so''mlik va 50 ming so''mlik banknotlarni qalbakilab, ularni mahalliy bozorda muomalada qila boshladi. U jami 5 million so''m qalbakilik pul muomalasi qilgani aniqlandi.', 
'1. Qalbakilik pul ishlab chiqarish. 2. Qalbakilik pul muomalasi qilish. 3. Qalbakilik pulning miqdori. 4. Ishlatilgan uskunalar.', 
ARRAY['176', '177', '178'], 
'Sud shaxsni qalbakilik pul ishlab chiqarish va muomalasi qilishda aybdor deb topdi. U 8 yilga ozodlikdan mahrum qilindi va qalbakilik pul ishlab chiqarishda ishlatilgan uskunalar musodara qilindi.', 
'Sud O''zbekiston Respublikasi Jinoyat kodeksining 176-moddasiga ko''ra, qalbakilik pul ishlab chiqarish - O''zbekiston Respublikasining milliy valyutasini qalbakilab ishlab chiqarish, qalbakilik pul muomalasi qilish yoki shunday puldan foydalanishdir. Erkakning harakatlari 176-moddasining tarkibiy belgilariga to''liq mos keladi.', 'high', 45, 90, 180, 'active', true, '2023-12-01', 1),

('770e8400-e29b-41d4-a716-446655440007', 'Navoiy viloyati "Navoiy" tumani sudi soliq to''lamaslik ishi', 
'Soliq to''lamaslik ma''muriy huquqbuzarligi bo''yicha sud hukmi. Tadbirkor soliq to''lamagani uchun jarima soldi.', 
'2023/567', 'Navoiy viloyati "Navoiy" tumani sudi', '2023-10-25', 'administrative', 'low', 
ARRAY['soliq', 'to''lash', 'tadbirkor', 'jarima'], 
'Navoiy viloyati "Navoiy" tumani yashovchi tadbirkor 2023-yil 1-yanvardan boshlab savdo faoliyati bilan shug''ullanadi. U davlat ro''yxatidan o''tgan bo''lishiga qaramay, 2023-yilning birinchi choragida soliq deklaratsiyasini topshirmagan. Soliq inspektsiyasi tekshiruv o''tkazib, tadbirkor 15 million so''m soliq to''lamaganini aniqladi.', 
'1. Soliq to''lamaslik ma''muriy huquqbuzarligi. 2. Soliq deklaratsiyasini topshirmaslik. 3. Soliq miqdori. 4. Tadbirkorning javobgarligi.', 
ARRAY['215', '226', '227'], 
'Sud tadbirkorni soliq to''lamaslikda aybdor deb topdi. U 15 million so''m miqdorida jarima soldi va soliqni to''lashga majbur qildi.', 
'Sud O''zbekiston Respublikasi Ma''muriy huquqbuzarliklar kodeksining 215-moddasiga ko''ra, soliq to''lash majburiyatini buzish - qonunda belgilangan tartibda soliqlarni to''lamaslik yoki toliq to''lamaslikdir. Tadbirkorning soliq deklaratsiyasini topshirmasligi va soliqni to''lamagani 215-moddasining tarkibiy belgilariga mos keladi.', 'low', 20, 30, 60, 'active', false, '2023-10-25', 1),

('770e8400-e29b-41d4-a716-446655440008', 'Jizzax viloyati "Jizzax" tumani sudi ruxsatsiz faoliyat ishi', 
'Ruxsat olinmagan faoliyat yuritish ma''muriy huquqbuzarligi bo''yicha sud hukmi. Shaxs litsenziyasiz tibbiyot faoliyati yuritgani uchun jarima soldi.', 
'2023/456', 'Jizzax viloyati "Jizzax" tumani sudi', '2023-11-20', 'administrative', 'medium', 
ARRAY['ruxsat', 'faoliyat', 'tibbiyot', 'litsenziya'], 
'Jizzax viloyati "Jizzax" tumani yashovchi 55 yoshli ayol 2023-yil iyul oyidan boshlab o''z uyida tibbiyot faoliyati bilan shug''ullanadi. U tibbiyot ma''lumotiga ega bo''lishiga qaramay, tibbiyot faoliyatini olib borish uchun ruxsat olmagan. U bemorlarni qabul qilib, ularni davolash bilan shug''ullanadi.', 
'1. Ruxsat olinmagan faoliyat yuritish. 2. Tibbiyot faoliyati litsenziyasiz olib borish. 3. Bemorlarni qabul qilish. 4. Sog''liqqa xavf tugdirish.', 
ARRAY['191', '192', '193'], 
'Sud ayolni ruxsat olinmagan tibbiyot faoliyati yuritishda aybdor deb topdi. U 10 million so''m miqdorida jarima soldi va faoliyatini to''xtatishga majbur qildi.', 
'Sud O''zbekiston Respublikasi Ma''muriy huquqbuzarliklar kodeksining 191-moddasiga ko''ra, davlat tomonidan berilgan ruxsatsiz faoliyat qilish - qonun hujjatlarida belgilangan tartibda ruxsat olinmagan faoliyat turlarini amalga oshirishdir. Ayolning tibbiyot faoliyatini litsenziyasiz olib borishi 191-moddasining tarkibiy belgilariga mos keladi.', 'medium', 25, 40, 80, 'active', false, '2023-11-20', 1),

('770e8400-e29b-41d4-a716-446655440009', 'Sirdaryo viloyati "Guliston" tumani sudi atrof-muhitni ifloslantirish ishi', 
'Atrof-muhitni muhofaza qilish talablarini buzish ma''muriy huquqbuzarligi bo''yicha sud hukmi. Korxona chiqindilarini noto''g''ri tashlagani uchun jarima soldi.', 
'2023/678', 'Sirdaryo viloyati "Guliston" tumani sudi', '2023-09-05', 'administrative', 'medium', 
ARRAY['atrof-muhit', 'ifloslantirish', 'chiqindi', 'korxona'], 
'Sirdaryo viloyati "Guliston" tumani yashovchi korxona egasi 2023-yil avgust oyidan boshlab o''z korxonasining chiqindilarini qonunda belgilangan tartibda tashlamaydi. U korxona chiqindilarini yaqin atrof-dagi yerga qo''yib, atrof-muhitni ifloslantirdi. Atrof-muhitni muhofaza qilish inspektsiyasi tekshiruv o''tkazib, qoidabuzarlikni aniqladi.', 
'1. Atrof-muhitni muhofaza qilish talablarini buzish. 2. Chiqindilarni noto''g''ri tashlash. 3. Atrof-muhitni ifloslantirish. 4. Korxona javobgarligi.', 
ARRAY['89', '90', '91'], 
'Sud korxona egasini atrof-muhitni muhofaza qilish talablarini buzishda aybdor deb topdi. U 20 million so''m miqdorida jarima soldi va chiqindilarni to''g''ri tashlashga majbur qildi.', 
'Sud O''zbekiston Respublikasi Ma''muriy huquqbuzarliklar kodeksining 89-moddasiga ko''ra, atrof-muhitni muhofaza qilish talablarini buzish - atrof-muhitni muhofaza qilish sohasidagi qonun hujjatlarida belgilangan talablarni buzishdir. Korxona egasining chiqindilarni noto''g''ri tashlashi 89-moddasining tarkibiy belgilariga mos keladi.', 'medium', 20, 35, 70, 'active', false, '2023-09-05', 1),

('770e8400-e29b-41d4-a716-446655440010', 'Toshkent shahar "Yashnobod" tumani sudi oilaviy nizol', 
'Ajrim va bolalar parvarishini aniqlash to''g''risidagi sud hukmi. Ajrim qilingan oilaning bolalari onasi bilan qoldi, otasi oylik to''lovni to''lashi belgilandi.', 
'2023/789', 'Toshkent shahar "Yashnobod" tumani sudi', '2023-12-15', 'civil', 'medium', 
ARRAY['ajrim', 'bolalar', 'parvarish', 'oylik to''lov'], 
'Toshkent shahar "Yashnobod" tumani yashovchi 32 yoshli ayol 2023-yil noyabr oyida eriga ajrim uchun sudga murojaat qildi. Ular 2018-yilda turmush qurishgan, 2 nafar farzandi bor: 5 yoshli o''g''il va 3 yoshli qiz. Ayol erining ichkilik munosabatlari va oilaviy zo''ravlikka sababli ajrimni so''raydi. Erkak ajrimga rozi bo''lmadi.', 
'1. Ajrim asoslari. 2. Bolalarning qaysi tarafda qolishi. 3. Oylik to''lov miqdori. 4. Mol-mulkni taqsimlash.', 
ARRAY['1', '126', '127', '128', '129', '130'], 
'Sud oilaviy munosabatlarni tiklash imkoni yo''qligini, bolalarning manfaatini inobatga olib, ajrimni qabul qildi. 5 yoshli o''g''il onasi bilan qoldi, 3 yoshli qiz esa otasi bilan qoldi. Erkak ayoliga har oy 2 million so''m miqdorida oylik to''lov to''lashi belgilandi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 126-moddasiga ko''ra, ajrim - oilaning sud tomonidan bekor qilishdir. Sud oilaviy munosabatlarni tiklash imkoni yo''qligini, bolalarning manfaatini inobatga olib, 126-moddasiga muvofiq ajrimni qabul qildi. Bolalarning qaysi tarafda qolishi 128-moddasiga ko''ra hal etildi.', 'medium', 25, 40, 80, 'active', false, '2023-12-15', 1),

('770e8400-e29b-41d4-a716-446655440011', 'Toshkent shahar "Mirzo-Ulug''bek" tumani sudi mehnat nizoli', 
'Ishdan bo''shatish to''g''risidagi sud hukmi. Ishchi haqsiz ishdan bo''shatilgani uchun ish beruvchi 5 million so''m miqdorida tovon to''lashi belgilandi.', 
'2023/890', 'Toshkent shahar "Mirzo-Ulug''bek" tumani sudi', '2023-11-30', 'civil', 'low', 
ARRAY['ishdan bo''shatish', 'ishchi', 'ish beruvchi', 'tovon'], 
'Toshkent shahar "Mirzo-Ulug''bek" tumani yashovchi 28 yoshli ayol 2023-yil yanvar oyidan boshlab "ABC" kompaniyada ishchi bo''lib ishladi. 2023-yil oktabr oyida kompaniya rahbariyati bilan kelishmovchilik tufayli sababsiz ishdan bo''shatildi. Ayol ish haqi to''lanmaganligini va ishdan haqsiz bo''shatilganini da''vo qilib sudga murojaat qildi.', 
'1. Ishdan bo''shatishning qonuniy asoslari. 2. Ishchi huquqlarining buzilishi. 3. Ish haqi to''lanmaganlik. 4. Tovon miqdori.', 
ARRAY['77', '240', '133'], 
'Sud ish beruvchining ayolni sababsiz ishdan bo''shatgani uchun javobgar ekanligini hukm qildi. Ish beruvchi ayolga 3 oylik ish haqi miqdorida tovon to''lashi va ishga tiklashni taklif qilish majburiyatini yukladi.', 
'Sud O''zbekiston Respublikasi Mehnat kodeksining 240-moddasiga ko''ra, ish beruvchining mehnat shartnomasini bir tomonlama bekor qilishi ishdan bo''shatish hisoblanadi. Ish beruvchining sababsiz ishchini ishdan bo''shatishi 240-moddasining 2-qismiga zid bo''lgani uchun sud ish beruvchini aybdeb topdi.', 'low', 15, 25, 50, 'active', false, '2023-11-30', 1),

('770e8400-e29b-41d4-a716-446655440012', 'Andijon viloyati "Andijon" tumani sudi vorislik nizoli', 
'Vorislik to''g''risidagi sud hukmi. Vafot etgan shaxsning mulki meros qilib olish to''g''risida nizol hal etildi.', 
'2023/234', 'Andijon viloyati "Andijon" tumani sudi', '2023-10-20', 'civil', 'medium', 
ARRAY['vorislik', 'meros', 'vafot', 'mol-mulk'], 
'Andijon viloyati "Andijon" tumani yashovchi 70 yoshli ayol 2023-yil avgust oyida vafot etdi. Uning 2 nafar farzandi bor: 45 yoshli o''g''il va 40 yoshli qiz. Ayol vafotidan oldin 100 million so''m miqdorida mulk qoldirdi. U vasiyatnomasida butun mulkini o''g''liga qoldirishini yozgan, ammo qizi bu vasiyatnomani tan olmadi.', 
'1. Vasiyatnomaning qonuniyligi. 2. Vorislik tartibi. 3. Qonuniy vorislar. 4. Mol-mulkning taqsimlanishi.', 
ARRAY['1120', '1121', '1122', '1123', '1124'], 
'Sud vasiyatnomaning qonuniyligini tan oldi. Ayolning o''g''li qonuniy voris sifatida meros qilib oldi. Qizining vasiyatnomani tan olmaganligi sababli, u merosdan mahrum qoldi. O''g''il opa-opaning meros qismini qiziga berishga majbur etildi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 1120-moddasiga ko''ra, vorislik - vafot etgan shaxsning mulkini qonunda belgilangan tartibda meros qilib olishdir. Ayolning o''g''li qonuniy voris sifatida meros qilib olishi 1120-moddasiga muvofiq.', 'medium', 30, 50, 100, 'active', false, '2023-10-20', 1),

('770e8400-e29b-41d4-a716-446655440013', 'Namangan viloyati "Namangan" tumani sudi mehnat shartnomasi nizoli', 
'Mehnat shartnomasini buzish to''g''risidagi sud hukmi. Ish beruvchi mehnat shartnomasidagi majburiyatlarini bajarmagani uchun javobgarlikka tortildi.', 
'2023/456', 'Namangan viloyati "Namangan" tumani sudi', '2023-08-25', 'civil', 'low', 
ARRAY['mehnat shartnomasi', 'buzish', 'ish beruvchi', 'ishchi'], 
'Namangan viloyati "Namangan" tumani yashovchi 25 yoshli erkak 2023-yil mart oyida "XYZ" korporatsiyasi bilan 1 yillik mehnat shartnomasi tuzdi. Shartnomaga ko''ra, u marketing bo''limi bo''lib ishlashi, oylik 5 million so''m maosh olishi kerak edi. Korporatsiya 3 oy davomida maoshni to''lamadi va ishchini ishdan bo''shatdi.', 
'1. Mehnat shartnomasining buzilishi. 2. Maosh to''lanmaganlik. 3. Ishdan bo''shatish. 4. Tovon talabi.', 
ARRAY['77', '133', '240'], 
'Sud korporatsiyani mehnat shartnomasidagi majburiyatlarini buzgani uchun aybdeb topdi. Korporatsiya ishchiga 3 oylik maosh miqdorida tovon to''lashi va ishga tiklash majburiyatini yukladi.', 
'Sud O''zbekiston Respublikasi Mehnat kodeksining 77-moddasiga ko''ra, mehnat shartnomasi - ishchi va ish beruvchi o''rtasida tuziladigan yozma shartnoma bo''lib, ularning huquq va majburiyatlarini belgilaydi. Korporatsiyaning shartnomadagi majburiyatlarini buzishi 77-moddasiga zid.', 'low', 20, 30, 60, 'active', false, '2023-08-25', 1),

('770e8400-e29b-41d4-a716-446655440014', 'Qoraqalpog''iston Respublikasi "Buxoro" tumani sudi kredit shartnomasi nizoli', 
'Kredit shartnomasi bo''yicha nizol. Bank kreditni o''z vaqtida qaytarmagani uchun foizlarni hisoblash talabi bilan murojaat qildi.', 
'2023/567', 'Qoraqalpog''iston Respublikasi "Buxoro" tumani sudi', '2023-12-05', 'civil', 'medium', 
ARRAY['kredit', 'foiz', 'bank', 'qaytarish'], 
'Qoraqalpog''iston Respublikasi "Buxoro" tumani yashovchi tadbirkor 2022-yil yanvar oyida "Kapitalbank" bilan 50 million so''m miqdorida kredit shartnomasini tuzdi. Shartnomaga ko''ra, kredit 1 yil muddatda 20 foiz stavkada qaytarilishi kerak edi. Tadbirkor kreditni o''z vaqtida qaytara olmadi va bank foizlarni hisoblash uchun sudga murojaat qildi.', 
'1. Kredit shartnomasining shartlari. 2. Kreditni qaytarmaslik. 3. Foiz stavkasi. 4. Bankning talablari.', 
ARRAY['777', '778', '779', '780'], 
'Sud kredit shartnomasining shartlariga rioya qilishni talab qildi. Tadbirkor kreditni asosiy summasini va foizlarni to''lashi kerakligi hukm qilindi. Bankning foizlarni hisoblash talabi qanoatlandirildi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 777-moddasiga ko''ra, kredit shartnomasi - bank yoki boshqa kredit tashkilotlari bilan kredit berish shartlarini belgilaydigan shartnoma. Tadbirkorning kredit shartnomasidagi majburiyatlarini buzishi 777-moddasiga zid.', 'medium', 35, 60, 120, 'active', false, '2023-12-05', 1),

('770e8400-e29b-41d4-a716-446655440015', 'Surxondaryo viloyati "Termiz" tumani sudi ijaraga berish shartnomasi nizoli', 
'Ijaraga berish shartnomasi bo''yicha nizol. Ijarachi mulkni buzgani uchun ijaraga beruvchi tovon talabi bilan murojaat qildi.', 
'2023/345', 'Surxondaryo viloyati "Termiz" tumani sudi', '2023-11-10', 'civil', 'low', 
ARRAY['ijara', 'buzish', 'tovon', 'ijarachi'], 
'Surxondaryo viloyati "Termiz" tumani yashovchi 30 yoshli erkak 2023-yil iyun oyida "ABC" uy-joy kompaniyasi bilan 1 yillik ijaraga berish shartnomasi tuzdi. U 2 xonali kvartirani ijaraga oldi va oylik 2 million so'm to''lashi kerak edi. Ijarachi 3 oydan keyin ijarani to''lashni to''xtatdi va kvartirani buzdi.', 
'1. Ijaraga berish shartnomasining buzilishi. 2. Ijarani to''lamaslik. 3. Mulkni buzish. 4. Tovon miqdori.', 
ARRAY['777', '771', '772'], 
'Sud ijarachining ijaraga berish shartnomasidagi majburiyatlarini buzgani uchun javobgar ekanligini hukm qildi. Ijarachi ijaraga beruvchiga 6 oylik ijarani to''lashi va buzilgan kvartira uchun tovon to''lashi belgilandi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 777-moddasiga ko''ra, ijaraga berish shartnomasi - ijaraga beruvchining ijarachiga mol-mulkni vaqtincha foydalanish huquqini berish va ijarachining ijarani to''lash majburiyatini belgilaydigan shartnoma. Ijarachining shartnomadagi majburiyatlarini buzishi 771-moddasiga zid.', 'low', 25, 40, 80, 'active', false, '2023-11-10', 1),

('770e8400-e29b-41d4-a716-446655440016', 'Toshkent shahar "Shayxontohur" tumani sudi nikoh nizoli', 
'Nikohning qonuniyligi to''g''risidagi sud hukmi. Nikoh qonunda belgilangan tartibda tuzilmagani uchun nikoh bekor qilindi.', 
'2023/678', 'Toshkent shahar "Shayxontohur" tumani sudi', '2023-07-20', 'civil', 'low', 
ARRAY['nikoh', 'qonuniylik', 'bekor qilish', 'ro''yxat'], 
'Toshkent shahar "Shayxontohur" tumani yashovchi 24 yoshli ayol va 26 yoshli erkak 2023-yil fevral oyida nikoh qurishdi. Ular diniy marosim o''tkazishmagan, faqat fuqarolik holatda ro''yxatdan o''tishmagan. 2023-yil iyun oyida ularning oilaviy munosabatlari yomonlashdi va ayol nikohni bekor qilish uchun sudga murojaat qildi.', 
'1. Nikohning qonuniyligi. 2. Fuqarolik holatda ro''yxatdan o''tish. 3. Oila to''g''risi. 4. Nikohni bekor qilish.', 
ARRAY['1', '8', '9', '10', '126'], 
'Sud nikohning qonuniyligini tan olmadi. Oila O''zbekiston Respublikasi Oilaviy kodeksining talablariga muvofiq tuzilmagani uchun nikoh bekor qilindi. Ikkala tomon ham erkin deb topildi.', 
'Sud O''zbekiston Respublikasi Oilaviy kodeksining 1-moddasiga ko''ra, nikoh - oila asosini tuzuvchi, qonunga muvofiq shaxslarning o''zaro huquq va majburiyatlari. Nikohning qonuniy bo''lmagani uchun nikoh bekor qilinishi mumkin.', 'low', 15, 25, 50, 'active', false, '2023-07-20', 1),

('770e8400-e29b-41d4-a716-446655440017', 'Toshkent shahar "Mirabad" tumani sudi vasiyatnoma nizoli', 
'Vasiyatnomaning shakliga oidai nizol. Vasiyatnomaning yozma shaklda tuzilmaganligi uchun u bekor qilindi.', 
'2023/234', 'Toshkent shahar "Mirabad" tumani sudi', '2023-09-15', 'civil', 'low', 
ARRAY['vasiyatnoma', 'shakl', 'beker qilish', 'meros'], 
'Toshkent shahar "Mirabad" tumani yashovchi 80 yoshli keksa 2023-yil avgust oyida vafot etdi. U o''limidan oldin og''zaki vasiyatnoma tuzdi, lekin uni yozma shaklda rasmiylashtirmadi. Vasiyatnomada u o''zining 2 xonali kvartirasini o''g''liga qoldirishini yozgan. Vafotidan keyin o''g''li vasiyatnomani da''vo qilib, meros qilib olishni talab qildi.', 
'1. Vasiyatnomaning shakli. 2. Yozma shaklda tuzilmaslik. 3. Vasiyatnomaning qonuniyligi. 4. Meros qilish tartibi.', 
ARRAY['1120', '1121', '1122', '1123'], 
'Sud vasiyatnomaning yozma shaklda tuzilmagani uchun uni bekor qilish hukmini chiqdi. Vafot etgan shaxsning mulki qonunda belgilangan tartibda meros qilib olishi kerak.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 1120-moddasiga ko''ra, vasiyatnoma - vafot etuvchi shaxsning o''z mulki va boshqa mol-mulkini o''limidan keyin boshqa shaxslarga o''tkazish haqidagi xohish-iradasi. Vasiyatnomaning yozma shaklda tuzilishi va notarial tasdig''i bilan tasdiqlanishi shart.', 'low', 20, 30, 60, 'active', false, '2023-09-15', 1),

('770e8400-e29b-41d4-a716-446655440018', 'Toshkent shahar "Chilonzor" tumani sudi shartnoma majburiyati nizoli', 
'Shartnoma majburiyatlarining bajarilmasligi to''g''risidagi nizol. Tomonlar shartnoma shartlarini bajarishmadi, sud javobgar tomonni majburiyatlarni bajarishga majbur qildi.', 
'2023/890', 'Toshkent shahar "Chilonzor" tumani sudi', '2023-10-30', 'civil', 'medium', 
ARRAY['shartnoma', 'majburiyat', 'bajarish', 'javobgar'], 
'Toshkent shahar "Chilonzor" tumani yashovchi 2 ta kompaniya o''rtasida 2023-yil yanvar oyida xizmat ko''rsatish shartnomasini tuzdilar. "A" kompaniyasi "B" kompaniyasiga marketing xizmatlarini ko''rsatishi, "B" kompaniyasi esa "A" kompaniyasiga IT xizmatlarini ko''rsatishi kerak edi. "A" kompaniyasi shartnomani bajarib, marketing xizmatlarini ko''rsatdi, ammo "B" kompaniyasi IT xizmatlarini to''liq bajarishdan bosh tortdi.', 
'1. Shartnoma majburiyatlari. 2. Ikkala tomonning majburiyatlari. 3. Bajarilmagan majburiyatlar. 4. Javobgarlik.', 
ARRAY['361', '366', '367'], 
'Sud "B" kompaniyasini shartnoma majburiyatlarini bajarishga majbur qildi. "A" kompaniyasiga tovon to''lash va "B" kompaniyasining majburiyatlari to''liq bajarilguncha shartnoma to''xtatilishi hukm qilindi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 361-moddasiga ko''ra, shartnoma yozma shaklda tuzilishi va tomonlar tomonidan imzolanishi kerak. Shartnomaning 366-moddasiga ko''ra, majburiyatlarni bajarish majburiyati bor.', 'medium', 30, 50, 100, 'active', false, '2023-10-30', 1),

('770e8400-e29b-41d4-a716-446655440019', 'Toshkent shahar "Yunusobod" tumani sudi mulkiy huquqbuzarlik nizoli', 
'Mulkkiy huquqbuzarlik buzilishi to''g''risidagi nizol. Shaxs boshqa kishining mulki huquqini buzgani uchun javobgarlikka tortildi.', 
'2023/456', 'Toshkent shahar "Yunusobod" tumani sudi', '2023-11-25', 'civil', 'medium', 
ARRAY['molkiy huquq', 'buzish', 'egalik', 'mulk'], 
'Toshkent shahar "Yunusobod" tumani yashovchi 35 yoshli erkak 2023-yil mart oyida "DEF" kompaniyasidan 20 million so''m miqdoridagi avtomashinani sotib oldi. U avtomashinani ro''yxatdan o''tkazdi, ammo pul to''lamadi. "DEF" kompaniyasi avtomashinani qaytarib olishni talab qildi, ammo erkak bu talabni rad etdi.', 
'1. Molkiy huquqbuzarlik buzilishi. 2. Mulk egalik huquqi. 3. Ro''yxatdan o''tkazish. 4. Pul to''lamaslik.', 
ARRAY['234', '235', '236', '237'], 
'Sud erkakning "DEF" kompaniyasining molkiy huquqbuzarligini buzgani uchun aybdeb topdi. Erkak avtomashinani qaytarib berishi va ro''yxatdan o''tkazishni amalga oshirishi kerakligi hukm qilindi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 234-moddasiga ko''ra, tovar-mulk huquqi - tovarlarga va boshqa mol-mulkka nisbatan fuqarolarning va fuqarolik bo''lmagan shaxslarning o''zlarining xohishlariga ko''ra egalik qilish, foydalanish, tasarruf etish va buyurtma berish huquqini anglatadi.', 'medium', 35, 60, 120, 'active', false, '2023-11-25', 1),

('770e8400-e29b-41d4-a716-446655440020', 'Toshkent shahar "Olmazar" tumani sudi himoya huquqbuzarlik nizoli', 
'Himoya huquqbuzarlik buzilishi to''g''risidagi nizol. Shaxs boshqa kishining shaxsiy huquqlarini buzgani uchun javobgarlikka tortildi.', 
'2023/567', 'Toshkent shahar "Olmazar" tumani sudi', '2023-12-20', 'civil', 'low', 
ARRAY['himoya huquq', 'shaxsiy huquq', 'buzish', 'javobgarlik'], 
'Toshkent shahar "Olmazar" tumani yashovchi 20 yoshli ayol 2023-yil oktabr oyida o''zining suratini ruxsatisiz ijtimiyot tarmoqlarida tarqatdi. Uning ruxsatisiz tarqalgan suratlari uchun ayolning shaxsiy huquqlari buzildi. Ayol bu holat uchun sudga murojaat qildi.', 
'1. Himoya huquqbuzarligi. 2. Shaxsiy huquqlar. 3. Ruxsatsiz foydalanish. 4. Javobgarlik.', 
ARRAY['27', '28', '29', '30'], 
'Sud ayolning shaxsiy huquqlarini buzgan shaxslarni javobgarlikka tortish talabini qanoatladi. Ruxsatsiz foydalanilgan suratlarni olib tashlash va ayolning shaxsiy huquqlarini tiklash choralarini ko''rish hukm qilindi.', 
'Sud O''zbekiston Respublikasi Fuqarolik kodeksining 27-moddasiga ko''ra, shaxsiy huquq - fuqarolarning va fuqarolik bo''lmagan shaxslarning o''zlarining shaxsiy nomini, shaxsiy yashash joyini, shaxsiy yashirinimni, shaxsiy tasvirini, oilaviy holatini, fuqarolik holatini va boshqa shaxsiy huquqlariga ega bo''lishi va ulardan foydalanish huquqini anglatadi.', 'low', 20, 35, 70, 'active', false, '2023-12-20', 1);

-- Update sequences for future inserts
SELECT setval(pg_get_serial_seq('laws_id_seq', (SELECT COALESCE(MAX(id), 20) FROM laws)));
SELECT setval(pg_get_serial_seq('clauses_id_seq', (SELECT COALESCE(MAX(id), 5) FROM clauses)));
SELECT setval(pg_get_serial_seq('cases_id_seq', (SELECT COALESCE(MAX(id), 20) FROM cases)));

COMMIT;
